<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProvaSuficienciaWebII.Application\ProvaSuficienciaWebII.Application.csproj" />
    <ProjectReference Include="..\ProvaSuficienciaWebII.Infrastructure\ProvaSuficienciaWebII.Infrastructure.csproj" />
    <ProjectReference Include="..\ProvaSuficienciaWebII.Contracts\ProvaSuficienciaWebII.Contracts.csproj" />
  </ItemGroup>

</Project>
